// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ExtensionDelegate
@end

@implementation GlanceController
@end

@implementation InterfaceController
@end

@implementation NotificationController
@end

@implementation SwitchRow
@end

