// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <WatchKit/WatchKit.h>
#import <Foundation/Foundation.h>

@interface ExtensionDelegate: NSObject
-(IBAction) applicationDidFinishLaunching;
-(IBAction) applicationDidBecomeActive;
-(IBAction) applicationWillResignActive;

@end

@interface GlanceController: WKInterfaceController
-(IBAction) awakeWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface InterfaceController: WKInterfaceController

@property IBOutlet WKInterfaceTable * switches_table;

-(IBAction) awakeWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface NotificationController: WKUserNotificationInterfaceController
-(IBAction) init;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface SwitchRow: NSObject

@property IBOutlet WKInterfaceSwitch * switch_item;

@end

